apiVersion: apps/v1
kind: Deployment
metadata:
  name: floor-cleaner-sales
  labels:
    app: floor-cleaner-sales
spec:
  replicas: 2
  selector:
    matchLabels:
      app: floor-cleaner-sales
  template:
    metadata:
      labels:
        app: floor-cleaner-sales
    spec:
      containers:
        - name: floor-cleaner-sales
          image: piyushdocker90/floor-cleaner-sales:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: floor-cleaner-sales
spec:
  selector:
    app: floor-cleaner-sales
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
